package fi.vm.yti.codelist.intake.exception;

public class ErrorConstants {

    public static final String ERR_MSG_USER_401 = "ERR_MSG_USER_401";
    public static final String ERR_MSG_USER_406 = "ERR_MSG_USER_406";
    public static final String ERR_MSG_USER_500 = "ERR_MSG_USER_500";
    public static final String ERR_MSG_USER_END_BEFORE_START_DATE = "ERR_MSG_USER_END_BEFORE_START_DATE";
    public static final String ERR_MSG_USER_ROW_MISSING_CODEVALUE = "ERR_MSG_USER_ROW_MISSING_CODEVALUE";
    public static final String ERR_MSG_USER_ROW_MISSING_STATUS = "ERR_MSG_USER_ROW_MISSING_STATUS";
    public static final String ERR_MSG_USER_MISSING_HEADER_CODEVALUE = "ERR_MSG_USER_MISSING_HEADER_CODEVALUE";
    public static final String ERR_MSG_USER_MISSING_HEADER_STATUS = "ERR_MSG_USER_MISSING_HEADER_STATUS";
    public static final String ERR_MSG_USER_ERRONEOUS_START_DATE = "ERR_MSG_USER_ERRONEOUS_START_DATE";
    public static final String ERR_MSG_USER_ERRONEOUS_END_DATE = "ERR_MSG_USER_ERRONEOUS_END_DATE";
    public static final String ERR_MSG_USER_ALREADY_EXISTING_CODE = "ERR_MSG_USER_ALREADY_EXISTING_CODE";
    public static final String ERR_MSG_USER_ALREADY_EXISTING_CODE_SCHEME = "ERR_MSG_USER_ALREADY_EXISTING_CODE_SCHEME";
    public static final String ERR_MSG_USER_HIERARCHY_LEVEL_INVALID_VALUE = "ERR_MSG_USER_HIERARCHY_LEVEL_INVALID_VALUE";
    public static final String ERR_MSG_USER_MISSING_HEADER_CLASSIFICATION = "ERR_MSG_USER_MISSING_HEADER_CLASSIFICATION";
    public static final String ERR_MSG_USER_BAD_CLASSIFICATION = "ERR_MSG_USER_BAD_CLASSIFICATION";
    public static final String ERR_MSG_EXISTING_CODE_MISMATCH = "ERR_MSG_EXISTING_CODE_MISMATCH";
    public static final String ERR_MSG_USER_ERROR_PARSING_EXCEL_FILE = "ERR_MSG_USER_ERROR_PARSING_EXCEL_FILE";
    public static final String ERR_MSG_USER_ERROR_PARSING_CSV_FILE = "ERR_MSG_USER_ERROR_PARSING_CSV_FILE";
    public static final String ERR_MSG_USER_DUPLICATE_HEADER_VALUE = "ERR_MSG_USER_DUPLICATE_HEADER_VALUE";
    public static final String ERR_MSG_BROADER_CODE_DOES_NOT_EXIST = "ERR_MSG_BROADER_CODE_DOES_NOT_EXIST";
    public static final String ERR_MSG_BROADER_CODE_SELF_REFERENCE = "ERR_MSG_BROADER_CODE_SELF_REFERENCE";
    public static final String ERR_MSG_STATUS_NOT_VALID = "ERR_MSG_STATUS_NOT_VALID";
}
