package fi.vm.yti.codelist.intake.exception;

public class ErrorConstants {

    public static final String ERR_MSG_USER_401 = "ERR_MSG_USER_401";
    public static final String ERR_MSG_USER_404 = "ERR_MSG_USER_404";
    public static final String ERR_MSG_USER_406 = "ERR_MSG_USER_406";
    public static final String ERR_MSG_USER_500 = "ERR_MSG_USER_500";
    public static final String ERR_MSG_USER_END_BEFORE_START_DATE = "ERR_MSG_USER_END_BEFORE_START_DATE";
    public static final String ERR_MSG_USER_ROW_MISSING_CODEVALUE = "ERR_MSG_USER_ROW_MISSING_CODEVALUE";
    public static final String ERR_MSG_USER_ROW_MISSING_PROPERTYTYPE = "ERR_MSG_USER_ROW_MISSING_PROPERTYTYPE";
    public static final String ERR_MSG_USER_ROW_MISSING_STATUS = "ERR_MSG_USER_ROW_MISSING_STATUS";
    public static final String ERR_MSG_USER_MISSING_HEADER_CODEVALUE = "ERR_MSG_USER_MISSING_HEADER_CODEVALUE";
    public static final String ERR_MSG_USER_MISSING_HEADER_STATUS = "ERR_MSG_USER_MISSING_HEADER_STATUS";
    public static final String ERR_MSG_USER_MISSING_HEADER_PROPERTYTYPE = "ERR_MSG_USER_MISSING_HEADER_PROPERTYTYPE";
    public static final String ERR_MSG_USER_ERRONEOUS_START_DATE = "ERR_MSG_USER_ERRONEOUS_START_DATE";
    public static final String ERR_MSG_USER_ERRONEOUS_END_DATE = "ERR_MSG_USER_ERRONEOUS_END_DATE";
    public static final String ERR_MSG_USER_ALREADY_EXISTING_CODE = "ERR_MSG_USER_ALREADY_EXISTING_CODE";
    public static final String ERR_MSG_USER_ALREADY_EXISTING_CODE_SCHEME = "ERR_MSG_USER_ALREADY_EXISTING_CODE_SCHEME";
    public static final String ERR_MSG_USER_HIERARCHY_LEVEL_INVALID_VALUE = "ERR_MSG_USER_HIERARCHY_LEVEL_INVALID_VALUE";
    public static final String ERR_MSG_USER_ORDER_INVALID_VALUE = "ERR_MSG_USER_ORDER_INVALID_VALUE";
    public static final String ERR_MSG_USER_MISSING_HEADER_CLASSIFICATION = "ERR_MSG_USER_MISSING_HEADER_CLASSIFICATION";
    public static final String ERR_MSG_USER_BAD_CLASSIFICATION = "ERR_MSG_USER_BAD_CLASSIFICATION";
    public static final String ERR_MSG_EXISTING_CODE_MISMATCH = "ERR_MSG_EXISTING_CODE_MISMATCH";
    public static final String ERR_MSG_USER_ERROR_PARSING_EXCEL_FILE = "ERR_MSG_USER_ERROR_PARSING_EXCEL_FILE";
    public static final String ERR_MSG_USER_ERROR_PARSING_CSV_FILE = "ERR_MSG_USER_ERROR_PARSING_CSV_FILE";
    public static final String ERR_MSG_USER_DUPLICATE_HEADER_VALUE = "ERR_MSG_USER_DUPLICATE_HEADER_VALUE";
    public static final String ERR_MSG_BROADER_CODE_DOES_NOT_EXIST = "ERR_MSG_BROADER_CODE_DOES_NOT_EXIST";
    public static final String ERR_MSG_BROADER_CODE_SELF_REFERENCE = "ERR_MSG_BROADER_CODE_SELF_REFERENCE";
    public static final String ERR_MSG_STATUS_NOT_VALID = "ERR_MSG_STATUS_NOT_VALID";
    public static final String ERR_MSG_DUPLICATE_CODE_VALUE = "ERR_MSG_DUPLICATE_CODE_VALUE";
    public static final String ERR_MSG_ID_MISMATCH = "ERR_MSG_ID_MISMATCH";
    public static final String ERR_MSG_PATH_CODE_MISMATCH = "ERR_MSG_PATH_CODE_MISMATCH";
    public static final String ERR_MSG_STATUS_CHANGE_NOT_ALLOWED = "ERR_MSG_STATUS_CHANGE_NOT_ALLOWED";
    public static final String ERR_MSG_INVALID_ID = "ERR_MSG_INVALID_ID";
    public static final String ERR_MSG_INVALID_CODE_CODEVALUE = "ERR_MSG_INVALID_CODE_CODEVALUE";
    public static final String ERR_MSG_INVALID_CODEVALUE = "ERR_MSG_INVALID_CODEVALUE";
    public static final String ERR_MSG_CANT_REACH_TERMINOLOGY_API = "ERR_MSG_CANT_REACH_TERMINOLOGY_API";
    public static final String ERR_MSG_USER_ROW_MISSING_EXTENSIONVALUE = "ERR_MSG_USER_ROW_MISSING_EXTENSIONVALUE";
    public static final String ERR_MSG_USER_ROW_MISSING_CODE = "ERR_MSG_USER_ROW_MISSING_CODE";
    public static final String ERR_MSG_CODE_ORDER_NOT_SEQUENTIAL = "ERR_MSG_CODE_ORDER_NOT_SEQUENTIAL";
    public static final String ERR_MSG_CODE_ORDER_ALREADY_IN_USE = "ERR_MSG_CODE_ORDER_ALREADY_IN_USE";
    public static final String ERR_MSG_CODE_ORDER_CONTAINS_DUPLICATE_VALUES = "ERR_MSG_CODE_ORDER_CONTAINS_DUPLICATE_VALUES";
    public static final String ERR_MSG_USER_EXTENSION_CODE_NOT_FOUND = "ERR_MSG_USER_EXTENSION_CODE_NOT_FOUND";
    public static final String ERR_MSG_USER_EXTENSION_CODE_NOT_ALLOWED = "ERR_MSG_USER_EXTENSION_CODE_NOT_ALLOWED";
    public static final String ERR_MSG_USER_EXTENSION_HIERARCHY_MAXLEVEL_REACHED = "ERR_MSG_USER_EXTENSION_HIERARCHY_MAXLEVEL_REACHED";
    public static final String ERR_MSG_USER_EXTENSIONSCHEME_CODESCHEME_NOT_FOUND = "ERR_MSG_USER_EXTENSIONSCHEME_CODESCHEME_NOT_FOUND";
    public static final String ERR_MSG_USER_EXTENSIONSCHEME_PROPERTYTYPE_NOT_FOUND = "ERR_MSG_USER_EXTENSIONSCHEME_PROPERTYTYPE_NOT_FOUND";

    private ErrorConstants() {
    }
}
